[build]
  publish = "."  # Deploy from root directory
  # No build command needed

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 
        'unsafe-inline' 
        https://cdnjs.cloudflare.com 
        https://www.youtube.com 
        https://www.google-analytics.com 
        https://cdn.skypack.dev;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data:;
      frame-src https://www.youtube.com;
      connect-src 'self';
      object-src 'none'
    """