[build]
  publish = "public"
  command = "echo 'No build needed'"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Security-Policy = "default-src 'self' https://*.cloudflare.com https://*.youtube.com; script-src 'self' 'unsafe-inline' https://*.cloudflare.com; style-src 'self' 'unsafe-inline'; frame-src https://*.youtube.com;"
